### ISSUE TITLE
有些服务器没被屏蔽，我使用的是今天的L4D2_IP_BLOCKER.json

### ISSUE THREAD

**Issue by Meow0x7E** [razerdp/L4D2_RPG_Blocker#1]
我总结了一下认为可以用这些正则表达式，对其名称进行匹配

```
\[HT\](一念仙行录|天选多特|玄灵秘境)\d+房
\[KR\]\[RPG\] Special Campaign
\w+無人永生RPG战役
```

以下这个我不确定，因为我无法进入那些服务器确认
```
\[AC\]\w+娱乐特色.APG服
```
里面的"."是因为那个五角星符号我无法输入所以用"."匹配
服务器IP: 103.45.162.183:20715 - 20722

**Comment by razerdp** [comment]
后续我打算迭代这个，模糊拦截。就是把拦截功能的做进来。
PS，我们这个软件不需要正则，都是模糊匹配的

**Comment by Meow0x7E** [comment]
明白了
